# Generated by Django 3.2.4 on 2024-01-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('movies', 'Movie'), ('games', 'Game'), ('books', 'Book'), ('comics', 'Comic')], default='movies', max_length=50),
        ),
    ]
